version: "3"
services:
  web:
    build: .
    environment:
      BCRYPT_SECRET: asdawqelkajsldakxqkuhweoihkdajnskajhdoas
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: angel 
volumes:
  db-volume:

